@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/aws.puml
!include FONTAWESOME/users.puml

title "Digital Wallet"
Person(CUSTOMER, "Customer", "Digital Wallet Customer", $sprite="users")
System(WALLET, "Digital Wallet System", "Full Cycle Digital Wallet")

System_Ext(SECRETS_MANAGER, "AWS Secret Manager", "Credentials Manager", $sprite="aws")
System_Ext(APM, "APM", "Application Performance Monitoring")
System_Ext(COLLECTOR, "OTEL Collector", "Open Telemetry Collector")
System_Ext(PAYMENT_GATEWAY, "Payment Gateway", "Processador de Pagamento")

Rel(CUSTOMER, WALLET, "Uses", "Https")
Rel(WALLET, SECRETS_MANAGER, "Uses", "Https")
Rel(WALLET, APM, "Uses", "Https")
Rel(WALLET, COLLECTOR, "Uses", "Https")
Rel(WALLET, PAYMENT_GATEWAY, "Uses", "Https")

@enduml
